Fixes for Kotlin 1.3 -> 1.4 binary compatibility
- avoid use of property and function references (`Foo::bar`)
- avoid use of delegated properties (unless inline)

Unfortunately these will cause `NoClassDefFoundError`s when compiled against Kotlin 1.4 stdlib and used from Kotlin 1.3 (Gradle pre 6.8)

Also use new version 0.2.0 of plugin-utils library which contains these fixes